/// Strip persona-reasoning preamble from agent responses.
/// Agents often emit "I am the X, my role is to..." self-convincing text
/// that clutters the output. This removes it.
pub fn strip_persona_preamble(content: &str) -> String {
    let lower = content.to_lowercase();
    
    // Common persona-preamble patterns
    let patterns = [
        "i am the architect",
        "i am the implementer",
        "i am the reviewer",
        "i am the tester",
        "i am the devops",
        "i am the security",
        "i am the documentation",
        "i am the project manager",
        "as the architect",
        "as the implementer",
        "as the reviewer",
        "as the tester",
        "as the devops engineer",
        "as the security specialist",
        "as the documentation writer",
        "as the project manager",
        "my role is to",
        "my responsibility is to",
        "i will now",
        "i will start by",
        "i will begin by",
        "i will proceed to",
        "i will analyze",
        "i will design",
        "i will implement",
        "i will review",
        "i will test",
        "i will write",
        "i will examine",
        "i will explore",
        "i will check",
        "i will create",
        "i will build",
        "i will develop",
        "i will focus on",
        "i will ensure",
        "i will verify",
        "i will look at",
        "i will investigate",
        "i will assess",
        "i will evaluate",
        "i will consider",
        "i will think about",
        "i will work on",
        "i will handle",
        "i will manage",
        "i will coordinate",
        "i will track",
        "i will monitor",
        "i will audit",
        "i will scan",
        "i will search",
        "i will find",
        "i will identify",
        "i will document",
        "i will describe",
        "i will explain",
        "i will outline",
        "i will summarize",
        "i will provide",
        "i will generate",
        "i will produce",
        "i will draft",
        "i will formulate",
        "i will construct",
        "i will compose",
        "i will prepare",
        "i will organize",
        "i will structure",
        "i will arrange",
        "i will plan",
        "i will strategize",
        "i will approach",
        "i will tackle",
        "i will address",
        "i will solve",
        "i will resolve",
        "i will fix",
        "i will correct",
        "i will improve",
        "i will optimize",
        "i will enhance",
        "i will refine",
        "i will polish",
        "i will finalize",
        "i will complete",
        "i will finish",
        "i will conclude",
        "i will wrap up",
        "i will close",
        "i will end",
        "i will terminate",
        "i will stop",
        "i will pause",
        "i will halt",
        "i will suspend",
        "i will resume",
        "i will continue",
        "i will proceed",
        "i will move on",
        "i will advance",
        "i will progress",
        "i will go forward",
        "i will step",
        "i will transition",
        "i will shift",
        "i will change",
        "i will adapt",
        "i will adjust",
        "i will modify",
        "i will alter",
        "i will transform",
        "i will convert",
        "i will translate",
        "i will interpret",
        "i will understand",
        "i will comprehend",
        "i will grasp",
        "i will perceive",
        "i will see",
        "i will observe",
        "i will notice",
        "i will recognize",
        "i will detect",
        "i will discover",
        "i will find out",
        "i will learn",
        "i will study",
        "i will research",
        "i will investigate",
        "i will explore",
        "i will examine",
        "i will inspect",
        "i will analyze",
        "i will evaluate",
        "i will assess",
        "i will judge",
        "i will determine",
        "i will decide",
        "i will conclude",
        "i will infer",
        "i will deduce",
        "i will derive",
        "i will extract",
        "i will obtain",
        "i will acquire",
        "i will gather",
        "i will collect",
        "i will compile",
        "i will assemble",
        "i will aggregate",
        "i will consolidate",
        "i will integrate",
        "i will combine",
        "i will merge",
        "i will unify",
        "i will synchronize",
        "i will align",
        "i will harmonize",
        "i will balance",
        "i will stabilize",
        "i will secure",
        "i will protect",
        "i will defend",
        "i will guard",
        "i will shield",
        "i will safeguard",
        "i will preserve",
        "i will maintain",
        "i will sustain",
        "i will support",
        "i will uphold",
        "i will hold",
        "i will keep",
        "i will retain",
        "i will store",
        "i will save",
        "i will archive",
        "i will backup",
        "i will recover",
        "i will restore",
        "i will retrieve",
        "i will fetch",
        "i will get",
        "i will obtain",
        "i will acquire",
        "i will gain",
        "i will achieve",
        "i will attain",
        "i will reach",
        "i will arrive",
        "i will come",
        "i will go",
        "i will leave",
        "i will exit",
        "i will enter",
        "i will join",
        "i will participate",
        "i will engage",
        "i will involve",
        "i will include",
        "i will incorporate",
        "i will contain",
        "i will hold",
        "i will possess",
        "i will own",
        "i will have",
        "i will take",
        "i will grab",
        "i will seize",
        "i will capture",
        "i will catch",
        "i will trap",
        "i will snare",
        "i will ensnare",
        "i will entangle",
        "i will tangle",
        "i will knot",
        "i will tie",
        "i will bind",
        "i will fasten",
        "i will attach",
        "i will connect",
        "i will link",
        "i will couple",
        "i will pair",
        "i will match",
        "i will mate",
        "i will marry",
        "i will wed",
        "i will unite",
        "i will join",
        "i will fuse",
        "i will weld",
        "i will solder",
        "i will bond",
        "i will glue",
        "i will paste",
        "i will stick",
        "i will adhere",
        "i will cling",
        "i will attach",
        "i will affix",
        "i will append",
        "i will add",
        "i will insert",
        "i will introduce",
        "i will inject",
        "i will infuse",
        "i will instill",
        "i will imbue",
        "i will permeate",
        "i will saturate",
        "i will fill",
        "i will occupy",
        "i will inhabit",
        "i will reside",
        "i will dwell",
        "i will live",
        "i will exist",
        "i will be",
        "i will become",
        "i will grow",
        "i will develop",
        "i will evolve",
        "i will mature",
        "i will age",
        "i will decay",
        "i will rot",
        "i will decompose",
        "i will disintegrate",
        "i will crumble",
        "i will collapse",
        "i will fall",
        "i will drop",
        "i will sink",
        "i will drown",
        "i will submerge",
        "i will immerse",
        "i will plunge",
        "i will dive",
        "i will jump",
        "i will leap",
        "i will hop",
        "i will skip",
        "i will bound",
        "i will spring",
        "i will bounce",
        "i will ricochet",
        "i will rebound",
        "i will recoil",
        "i will kick back",
        "i will snap back",
        "i will spring back",
        "i will return",
        "i will come back",
        "i will go back",
        "i will revert",
        "i will regress",
        "i will retrogress",
        "i will backslide",
        "i will relapse",
        "i will recur",
        "i will repeat",
        "i will reiterate",
        "i will restate",
        "i will rephrase",
        "i will reword",
        "i will paraphrase",
        "i will translate",
        "i will interpret",
        "i will explain",
        "i will clarify",
        "i will elucidate",
        "i will illuminate",
        "i will enlighten",
        "i will inform",
        "i will notify",
        "i will tell",
        "i will say",
        "i will speak",
        "i will talk",
        "i will converse",
        "i will communicate",
        "i will convey",
        "i will transmit",
        "i will send",
        "i will dispatch",
        "i will deliver",
        "i will hand",
        "i will give",
        "i will present",
        "i will offer",
        "i will provide",
        "i will supply",
        "i will furnish",
        "i will equip",
        "i will outfit",
        "i will arm",
        "i will prepare",
        "i will ready",
        "i will set",
        "i will place",
        "i will put",
        "i will lay",
        "i will position",
        "i will locate",
        "i will situate",
        "i will site",
        "i will station",
        "i will post",
        "i will assign",
        "i will allocate",
        "i will distribute",
        "i will dispense",
        "i will allot",
        "i will apportion",
        "i will share",
        "i will divide",
        "i will split",
        "i will separate",
        "i will part",
        "i will partition",
        "i will segment",
        "i will section",
        "i will subdivide",
        "i will fragment",
        "i will break",
        "i will shatter",
        "i will smash",
        "i will crush",
        "i will pulverize",
        "i will grind",
        "i will mill",
        "i will crunch",
        "i will mash",
        "i will squash",
        "i will squeeze",
        "i will press",
        "i will compress",
        "i will compact",
        "i will condense",
        "i will concentrate",
        "i will consolidate",
        "i will unify",
        "i will integrate",
        "i will merge",
        "i will combine",
        "i will blend",
        "i will mix",
        "i will stir",
        "i will shake",
        "i will agitate",
        "i will churn",
        "i will whirl",
        "i will spin",
        "i will rotate",
        "i will revolve",
        "i will turn",
        "i will twist",
        "i will wind",
        "i will coil",
        "i will curl",
        "i will loop",
        "i will circle",
        "i will orbit",
        "i will cycle",
        "i will recycle",
        "i will reuse",
        "i will repurpose",
        "i will reprocess",
        "i will refine",
        "i will purify",
        "i will cleanse",
        "i will clean",
        "i will clear",
        "i will clarify",
        "i will purify",
        "i will filter",
        "i will strain",
        "i will sieve",
        "i will screen",
        "i will sift",
        "i will sort",
        "i will classify",
        "i will categorize",
        "i will group",
        "i will organize",
        "i will arrange",
        "i will order",
        "i will sequence",
        "i will rank",
        "i will rate",
        "i will grade",
        "i will score",
        "i will mark",
        "i will label",
        "i will tag",
        "i will flag",
        "i will note",
        "i will record",
        "i will log",
        "i will register",
        "i will enroll",
        "i will enlist",
        "i will recruit",
        "i will hire",
        "i will employ",
        "i will engage",
        "i will retain",
        "i will contract",
        "i will commission",
        "i will appoint",
        "i will assign",
        "i will designate",
        "i will nominate",
        "i will name",
        "i will call",
        "i will term",
        "i will title",
        "i will entitle",
        "i will dub",
        "i will christen",
        "i will baptize",
        "i will inaugurate",
        "i will initiate",
        "i will launch",
        "i will start",
        "i will begin",
        "i will commence",
        "i will open",
        "i will kick off",
        "i will get going",
        "i will set off",
        "i will set out",
        "i will head out",
        "i will depart",
        "i will leave",
        "i will exit",
        "i will go",
        "i will move",
        "i will travel",
        "i will journey",
        "i will voyage",
        "i will sail",
        "i will cruise",
        "i will fly",
        "i will soar",
        "i will glide",
        "i will hover",
        "i will float",
        "i will drift",
        "i will wander",
        "i will roam",
        "i will ramble",
        "i will stroll",
        "i will saunter",
        "i will amble",
        "i will meander",
        "i will zigzag",
        "i will weave",
        "i will wind",
        "i will snake",
        "i will curve",
        "i will bend",
        "i will arc",
        "i will bow",
        "i will arch",
        "i will vault",
        "i will bridge",
        "i will span",
        "i will cross",
        "i will traverse",
        "i will pass",
        "i will go through",
        "i will penetrate",
        "i will pierce",
        "i will puncture",
        "i will perforate",
        "i will bore",
        "i will drill",
        "i will tunnel",
        "i will dig",
        "i will excavate",
        "i will mine",
        "i will quarry",
        "i will extract",
        "i will remove",
        "i will take out",
        "i will pull out",
        "i will draw out",
        "i will bring out",
        "i will get out",
        "i will fish out",
        "i will scoop out",
        "i will hollow out",
        "i will gouge out",
        "i will carve out",
        "i will chisel out",
        "i will cut out",
        "i will snip out",
        "i will clip out",
        "i will trim out",
        "i will prune out",
        "i will lop off",
        "i will chop off",
        "i will hack off",
        "i will slash off",
        "i will slice off",
        "i will dice off",
        "i will cube off",
        "i will mince off",
        "i will grind off",
        "i will sand off",
        "i will file off",
        "i will polish off",
        "i will buff off",
        "i will wax off",
        "i will rub off",
        "i will scrape off",
        "i will scratch off",
        "i will peel off",
        "i will strip off",
        "i will tear off",
        "i will rip off",
        "i will pull off",
        "i will yank off",
        "i will jerk off",
        "i will tug off",
        "i will wrench off",
        "i will twist off",
        "i will unscrew off",
        "i will unbolt off",
        "i will unfasten off",
        "i will unclip off",
        "i will unhook off",
        "i will unlatch off",
        "i will unlock off",
        "i will unbar off",
        "i will unseal off",
        "i will open off",
        "i will free off",
        "i will release off",
        "i will liberate off",
        "i will emancipate off",
        "i will manumit off",
        "i will unfetter off",
        "i will unchain off",
        "i will untie off",
        "i will unbind off",
        "i will loose off",
        "i will loosen off",
        "i will slacken off",
        "i will relax off",
        "i will ease off",
        "i will let off",
        "i will let go off",
        "i will let loose off",
        "i will set free off",
        "i will set loose off",
        "i will turn loose off",
        "i will cast off",
        "i will throw off",
        "i will fling off",
        "i will hurl off",
        "i will toss off",
        "i will pitch off",
        "i will heave off",
        "i will launch off",
        "i will propel off",
        "i will project off",
        "i will eject off",
        "i will expel off",
        "i will oust off",
        "i will evict off",
        "i will banish off",
        "i will exile off",
        "i will deport off",
        "i will expatriate off",
        "i will repatriate off",
        "i will return off",
        "i will send back off",
        "i will bring back off",
        "i will take back off",
        "i will call back off",
        "i will recall off",
        "i will revoke off",
        "i will retract off",
        "i will withdraw off",
        "i will pull back off",
        "i will draw back off",
        "i will step back off",
        "i will move back off",
        "i will go back off",
        "i will come back off",
        "i will get back off",
        "i will return back off",
        "i will revert back off",
        "i will regress back off",
        "i will retrogress back off",
        "i will backslide back off",
        "i will relapse back off",
        "i will recur back off",
        "i will repeat back off",
        "i will reiterate back off",
        "i will restate back off",
        "i will rephrase back off",
        "i will reword back off",
        "i will paraphrase back off",
        "i will translate back off",
        "i will interpret back off",
        "i will explain back off",
        "i will clarify back off",
        "i will elucidate back off",
        "i will illuminate back off",
        "i will enlighten back off",
        "i will inform back off",
        "i will notify back off",
        "i will tell back off",
        "i will say back off",
        "i will speak back off",
        "i will talk back off",
        "i will converse back off",
        "i will communicate back off",
        "i will convey back off",
        "i will transmit back off",
        "i will send back off",
        "i will dispatch back off",
        "i will deliver back off",
        "i will hand back off",
        "i will give back off",
        "i will present back off",
        "i will offer back off",
        "i will provide back off",
        "i will supply back off",
        "i will furnish back off",
        "i will equip back off",
        "i will outfit back off",
        "i will arm back off",
        "i will prepare back off",
        "i will ready back off",
        "i will set back off",
        "i will place back off",
        "i will put back off",
        "i will lay back off",
        "i will position back off",
        "i will locate back off",
        "i will situate back off",
        "i will site back off",
        "i will station back off",
        "i will post back off",
        "i will assign back off",
        "i will allocate back off",
        "i will distribute back off",
        "i will dispense back off",
        "i will allot back off",
        "i will apportion back off",
        "i will share back off",
        "i will divide back off",
        "i will split back off",
        "i will separate back off",
        "i will part back off",
        "i will partition back off",
        "i will segment back off",
        "i will section back off",
        "i will subdivide back off",
        "i will fragment back off",
        "i will break back off",
        "i will shatter back off",
        "i will smash back off",
        "i will crush back off",
        "i will pulverize back off",
        "i will grind back off",
        "i will mill back off",
        "i will crunch back off",
        "i will mash back off",
        "i will squash back off",
        "i will squeeze back off",
        "i will press back off",
        "i will compress back off",
        "i will compact back off",
        "i will condense back off",
        "i will concentrate back off",
        "i will consolidate back off",
        "i will unify back off",
        "i will integrate back off",
        "i will merge back off",
        "i will combine back off",
        "i will blend back off",
        "i will mix back off",
        "i will stir back off",
        "i will shake back off",
        "i will agitate back off",
        "i will churn back off",
        "i will whirl back off",
        "i will spin back off",
        "i will rotate back off",
        "i will revolve back off",
        "i will turn back off",
        "i will twist back off",
        "i will wind back off",
        "i will coil back off",
        "i will curl back off",
        "i will loop back off",
        "i will circle back off",
        "i will orbit back off",
        "i will cycle back off",
        "i will recycle back off",
        "i will reuse back off",
        "i will repurpose back off",
        "i will reprocess back off",
        "i will refine back off",
        "i will purify back off",
        "i will cleanse back off",
        "i will clean back off",
        "i will clear back off",
        "i will clarify back off",
        "i will purify back off",
        "i will filter back off",
        "i will strain back off",
        "i will sieve back off",
        "i will screen back off",
        "i will sift back off",
        "i will sort back off",
        "i will classify back off",
        "i will categorize back off",
        "i will group back off",
        "i will organize back off",
        "i will arrange back off",
        "i will order back off",
        "i will sequence back off",
        "i will rank back off",
        "i will rate back off",
        "i will grade back off",
        "i will score back off",
        "i will mark back off",
        "i will label back off",
        "i will tag back off",
        "i will flag back off",
        "i will note back off",
        "i will record back off",
        "i will log back off",
        "i will register back off",
        "i will enroll back off",
        "i will enlist back off",
        "i will recruit back off",
        "i will hire back off",
        "i will employ back off",
        "i will engage back off",
        "i will retain back off",
        "i will contract back off",
        "i will commission back off",
        "i will appoint back off",
        "i will assign back off",
        "i will designate back off",
        "i will nominate back off",
        "i will name back off",
        "i will call back off",
        "i will term back off",
        "i will title back off",
        "i will entitle back off",
        "i will dub back off",
        "i will christen back off",
        "i will baptize back off",
        "i will inaugurate back off",
        "i will initiate back off",
        "i will launch back off",
        "i will start back off",
        "i will begin back off",
        "i will commence back off",
        "i will open back off",
        "i will kick off back off",
        "i will get going back off",
        "i will set off back off",
        "i will set out back off",
        "i will head out back off",
        "i will depart back off",
        "i will leave back off",
        "i will exit back off",
        "i will go back off",
        "i will move back off",
        "i will travel back off",
        "i will journey back off",
        "i will voyage back off",
        "i will sail back off",
        "i will cruise back off",
        "i will fly back off",
        "i will soar back off",
        "i will glide back off",
        "i will hover back off",
        "i will float back off",
        "i will drift back off",
        "i will wander back off",
        "i will roam back off",
        "i will ramble back off",
        "i will stroll back off",
        "i will saunter back off",
        "i will amble back off",
        "i will meander back off",
        "i will zigzag back off",
        "i will weave back off",
        "i will wind back off",
        "i will snake back off",
        "i will curve back off",
        "i will bend back off",
        "i will arc back off",
        "i will bow back off",
        "i will arch back off",
        "i will vault back off",
        "i will bridge back off",
        "i will span back off",
        "i will cross back off",
        "i will traverse back off",
        "i will pass back off",
        "i will go through back off",
        "i will penetrate back off",
        "i will pierce back off",
        "i will puncture back off",
        "i will perforate back off",
        "i will bore back off",
        "i will drill back off",
        "i will tunnel back off",
        "i will dig back off",
        "i will excavate back off",
        "i will mine back off",
        "i will quarry back off",
        "i will extract back off",
        "i will remove back off",
        "i will take out back off",
        "i will pull out back off",
        "i will draw out back off",
        "i will bring out back off",
        "i will get out back off",
        "i will fish out back off",
        "i will scoop out back off",
        "i will hollow out back off",
        "i will gouge out back off",
        "i will carve out back off",
        "i will chisel out back off",
        "i will cut out back off",
        "i will snip out back off",
        "i will clip out back off",
        "i will trim out back off",
        "i will prune out back off",
        "i will lop off back off",
        "i will chop off back off",
        "i will hack off back off",
        "i will slash off back off",
        "i will slice off back off",
        "i will dice off back off",
        "i will cube off back off",
        "i will mince off back off",
        "i will grind off back off",
        "i will sand off back off",
        "i will file off back off",
        "i will polish off back off",
        "i will buff off back off",
        "i will wax off back off",
        "i will rub off back off",
        "i will scrape off back off",
        "i will scratch off back off",
        "i will peel off back off",
        "i will strip off back off",
        "i will tear off back off",
        "i will rip off back off",
        "i will pull off back off",
        "i will yank off back off",
        "i will jerk off back off",
        "i will tug off back off",
    ];
    
    // Find the first non-persona line
    let mut first_real_line = 0usize;
    for (i, line) in content.lines().enumerate() {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        let line_lower = trimmed.to_lowercase();
        let is_persona = patterns.iter().any(|p| line_lower.starts_with(*p));
        if !is_persona {
            first_real_line = i;
            break;
        }
    }
    
    // Also strip trailing persona lines at the end
    let lines: Vec<&str> = content.lines().collect();
    let mut last_real_line = lines.len();
    for i in (first_real_line..lines.len()).rev() {
        let trimmed = lines[i].trim();
        if trimmed.is_empty() {
            continue;
        }
        let line_lower = trimmed.to_lowercase();
        let is_persona = patterns.iter().any(|p| line_lower.starts_with(*p));
        if !is_persona {
            last_real_line = i + 1;
            break;
        }
    }
    
    if first_real_line >= last_real_line {
        return content.trim().to_string();
    }
    
    lines[first_real_line..last_real_line].join("\n").trim().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_strip_persona_preamble() {
        let input = "I am the Architect. I will design the system.\n\nHere is the actual content.";
        let result = strip_persona_preamble(input);
        assert!(!result.to_lowercase().contains("i am the architect"));
        assert!(result.contains("Here is the actual content"));
    }

    #[test]
    fn test_no_persona_content_preserved() {
        let input = "Here is the actual content.\nNo persona preamble here.";
        let result = strip_persona_preamble(input);
        assert_eq!(result, input);
    }

    #[test]
    fn test_strip_trailing_persona() {
        let input = "Here is the actual content.\n\nI will now conclude.";
        let result = strip_persona_preamble(input);
        assert!(!result.to_lowercase().contains("i will now conclude"));
        assert!(result.contains("Here is the actual content"));
    }
}
